environment            = "prod"
project_slug           = "squad-app"
git_repo               = "bbyvfrd/squad_app" # only prod links Git (PR previews)
supabase_org_id        = "huddbyyngwpgclzfgcmo"
supabase_region        = "eu-central-1"
supabase_instance_size = null # free-plan org can't set compute size; use "small"+ on a paid plan
app_site_url           = "https://squad-app-prod.vercel.app"
app_domain             = ""
vercel_team            = null
